### ISSUE TITLE
Error on compiling the code

### ISSUE THREAD

**Issue by DE8MSH** [Moonspine/snes-jukebox#1]
Hallo Moonspine.

I just downloaded the v1.0.5 of Arduino for Linux. And the both -- latest -- libraries Adafruit_GFX and Adafruit_ST7735. But this error appears when I want to compile it:

`In file included from /media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST7735.h:4,
                 from SNES_Jukebox.ino:5:
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:87: error: expected class-name before ‘{’ token
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:102: error: ISO C++ forbids initialization of member ‘_colstart’
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:102: error: making ‘_colstart’ static
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:102: error: ISO C++ forbids in-class initialization of non-const static member ‘_colstart’
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:103: error: ISO C++ forbids initialization of member ‘_rowstart’
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:103: error: making ‘_rowstart’ static
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:103: error: ISO C++ forbids in-class initialization of non-const static member ‘_rowstart’
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:104: error: ISO C++ forbids initialization of member ‘spiMode’
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:104: error: making ‘spiMode’ static
/media/marco/windowsprge/arduino-1.0.5/libraries/AdafruitST7735/Adafruit_ST77xx.h:104: error: ISO C++ forbids in-class initialization of non-const static member ‘spiMode’
In file included from port_write_menu.h:6,
                 from SNES_Jukebox.ino:14:
lcd_draw.h: In function ‘void clearLcd(Adafruit_ST7735&)’:
lcd_draw.h:9: error: ‘class Adafruit_ST7735’ has no member named ‘fillScreen’
lcd_draw.h: In function ‘void drawText(Adafruit_ST7735&, const char*, int, int, bool)’:
lcd_draw.h:13: error: ‘class Adafruit_ST7735’ has no member named ‘setCursor’
lcd_draw.h:14: error: ‘class Adafruit_ST7735’ has no member named ‘setTextColor’
lcd_draw.h:15: error: ‘class Adafruit_ST7735’ has no member named ‘setTextWrap’
lcd_draw.h:16: error: ‘class Adafruit_ST7735’ has no member named ‘print’
lcd_draw.h: In function ‘void drawIcon(Adafruit_ST7735&, prog_uint16_t*, int, int)’:
lcd_draw.h:101: error: ‘class Adafruit_ST7735’ has no member named ‘drawPixel’
In file included from SNES_Jukebox.ino:14:
port_write_menu.h: In member function ‘void PortWriteMenu::drawPorts(Adafruit_ST7735&, byte, const byte*)’:
port_write_menu.h:132: error: ‘class Adafruit_ST7735’ has no member named ‘fillRect’
port_write_menu.h: In member function ‘void PortWriteMenu::drawSelectionReticule(Adafruit_ST7735&, byte)’:
port_write_menu.h:177: error: ‘class Adafruit_ST7735’ has no member named ‘drawRect’
In file included from SNES_Jukebox.ino:18:
progress_bar.h: In constructor ‘ProgressBar::ProgressBar(Adafruit_ST7735&, byte, byte, byte, uint32_t)’:
progress_bar.h:16: error: ‘class Adafruit_ST7735’ has no member named ‘drawRect’
progress_bar.h:17: error: ‘class Adafruit_ST7735’ has no member named ‘fillRect’
progress_bar.h: In member function ‘void ProgressBar::addProgress(uint32_t)’:
progress_bar.h:30: error: ‘class Adafruit_ST7735’ has no member named ‘fillRect’
SNES_Jukebox.ino: In function ‘void drawFileSelection()’:
SNES_Jukebox:354: error: ‘class Adafruit_ST7735’ has no member named ‘fillRect’
`

Which versions of the libs did you use? Can you help me please. I realy want to buld this project.

Thank you very much.

**Comment by DE8MSH** [comment]
Now I'm using **Adafruit GFX Library 1.0.0** and **Adafruit ST7735 1.0.4**. With Arduino 1.0.5-r2 on WIndows or 1.0.5 on Ubuntu. It seems to compile now. Okay. There are some warnings:

`In file included from F:\arduino-1.0.5-r2\libraries\Firmata/Firmata.h:16,
                 from SNES_Jukebox.ino:1:
F:\arduino-1.0.5-r2\libraries\Firmata/Boards.h: In function 'unsigned char writePort(byte, byte, byte)':
F:\arduino-1.0.5-r2\libraries\Firmata/Boards.h:355: warning: no return statement in function returning non-void
In file included from SNES_Jukebox.ino:7:
/defines.h: At global scope:
/defines.h:11: warning: only initialized variables can be placed into program memory area
/defines.h:53: warning: only initialized variables can be placed into program memory area
/defines.h:71: warning: only initialized variables can be placed into program memory area
In file included from SNES_Jukebox.ino:9:
/spc_info.h: In member function 'void SPCInfo::parseSPC(File&)':
/spc_info.h:48: warning: comparison between signed and unsigned integer expressions
In file included from SNES_Jukebox.ino:11:
/file_list_menu.h: In member function 'void FileListMenu::resetPage()':
/file_list_menu.h:61: warning: comparison between signed and unsigned integer expressions
In file included from SNES_Jukebox.ino:12:
/port_write_menu.h: At global scope:
/port_write_menu.h:9: warning: only initialized variables can be placed into program memory area
/port_write_menu.h:10: warning: only initialized variables can be placed into program memory area
/port_write_menu.h:11: warning: only initialized variables can be placed into program memory area
/port_write_menu.h:12: warning: only initialized variables can be placed into program memory area
In file included from SNES_Jukebox.ino:13:
/icons.h:4: warning: only initialized variables can be placed into program memory area
/icons.h:16: warning: only initialized variables can be placed into program memory area
/icons.h:28: warning: only initialized variables can be placed into program memory area
/icons.h:40: warning: only initialized variables can be placed into program memory area
In file included from SNES_Jukebox.ino:15:
/brr_streamer.h: In function 'void uploadBrrBlock(byte*, int)':
/brr_streamer.h:72: warning: comparison between signed and unsigned integer expressions
/brr_streamer.h:73: warning: comparison between signed and unsigned integer expressions
/brr_streamer.h: In function 'void streamBrrFile(File&, Adafruit_ST7735&)':
/brr_streamer.h:113: warning: comparison between signed and unsigned integer expressions
SNES_Jukebox.ino: In function 'byte readDspRamData(File&, byte*)':
SNES_Jukebox.ino:155: warning: no return statement in function returning non-void
SNES_Jukebox.ino: In function 'void writeBytes(byte*, word)':
SNES_Jukebox.ino:201: warning: comparison between signed and unsigned integer expressions
SNES_Jukebox.ino: In function 'void loop()':
SNES_Jukebox.ino:392: warning: deprecated conversion from string constant to 'char*'
SNES_Jukebox.ino:465: warning: deprecated conversion from string constant to 'char*'
SNES_Jukebox.ino: In function 'byte readDspRamData(File&, byte*)':
SNES_Jukebox.ino:155: warning: control reaches end of non-void function
/spc_info.h: In member function 'void SPCInfo::parseSPC(File&)':
/spc_info.h:45: warning: 'lastByte' may be used uninitialized in this function`

I dont know if it's okay. But the main problem is: It breaks at 95% of the upload. 
Error message is:

`avrdude: stk500_paged_write(): (a) protocol error, expect=0x14, resp=0x64
avrdude: stk500_cmd(): programmer is out of sync`

I'm using the Arduino Uno board.

**Comment by DE8MSH** [comment]
Upload error says:

```
8< 8< 8< 8<
[08] . [95] . [e5] . [df] . [a0] . [f0] . [be] . [e7] . [b9] . [17] . [88] . [f4] . [bb] ' [27] . [9f] 8 [38] ` [60] . [f4] . [16] . [16] . [b1] . [1d] g [67] / [2f] x [78] / [2f] . [88] ' [27] . [98] _ [5f] . [f7] . [cf] . [86] . [95] w [77] . [95] g [67] . [95] . [b1] . [1d] . [93] . [95] . [96] 9 [39] . [c8] . [f3] . [08] . [95] . [e8] . [94] . [bb] ' [27] f [66] ' [27] w [77] ' [27] . [cb] . [01] . [97] . [f9] . [08] . [95] . [0b] . [d0] . [ad] . [cf] . [9e] . [df] ( [28] . [f0] . [a3] . [df] . [18] . [f0] . [95] # [23] . [09] . [f0] d [64] . [cf] . [94] . [cf] . [11] $ [24]   [20] 
avrdude: Recv: 

avrdude: stk500_paged_write(): (a) protocol error, expect=0x14, resp=0x64
avrdude: Send: V [56] @ [40] . [00] . [00] . [0c]   [20] 
avrdude: Recv: 
avrdude: stk500_cmd(): programmer is out of sync
```

If I upload "Blinki" sketch it works flawlessly.

**Comment by Moonspine** [comment]
You need some very specific versions of the Adafruit_GFX and Adafruit_ST7735, which I failed to specify in the readme (sorry about that). If you grab these versions, you should be good to go:

- Adafruit GFX library 1.0.2 (commit hash 4edc8942c46e7aeff; See https://github.com/adafruit/Adafruit-GFX-Library/commit/4edc8942c46e7aeff383d00576d71d6b9068e4a8 )
- Adafruit ST7735 library 1.0.4 (Commit hash 74238f6ea8db16f2b; See https://github.com/adafruit/Adafruit-ST7735-Library/commit/74238f6ea8db16f2bfe76e7aee852d536e158e50 )
